// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/powercore_pins.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::PROTECTED_PIN_0, // HP1
	Gpio::PROTECTED_PIN_1, // HP2
	Gpio::PROTECTED_PIN_2, // HP3
	Gpio::PROTECTED_PIN_3, // HP4
	Gpio::PROTECTED_PIN_4, // ADIO1
	Gpio::PROTECTED_PIN_5, // ADIO2
	Gpio::PROTECTED_PIN_6, // ADIO3
	Gpio::PROTECTED_PIN_7, // ADIO4
	Gpio::D2, // ADIO5
	Gpio::G11, // ADIO6
	Gpio::G3, // ADIO7
	Gpio::G4, // ADIO8
// "HP1",
// "HP2",
// "HP3",
// "HP4",
// "ADIO1",
// "ADIO2",
// "ADIO3",
// "ADIO4",
// "ADIO5",
// "ADIO6",
// "ADIO7",
// "ADIO8",
}
