// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/powercore_pins.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::PROTECTED_PIN_0:
			return "HP1";
		case Gpio::PROTECTED_PIN_1:
			return "HP2";
		case Gpio::PROTECTED_PIN_2:
			return "HP3";
		case Gpio::PROTECTED_PIN_3:
			return "HP4";
		case Gpio::PROTECTED_PIN_4:
			return "ADIO1";
		case Gpio::PROTECTED_PIN_5:
			return "ADIO2";
		case Gpio::PROTECTED_PIN_6:
			return "ADIO3";
		case Gpio::PROTECTED_PIN_7:
			return "ADIO4";
		case Gpio::PROTECTED_PIN_8:
			return "ADIO5";
		case Gpio::PROTECTED_PIN_9:
			return "ADIO6";
		case Gpio::PROTECTED_PIN_10:
			return "ADIO7";
		case Gpio::PROTECTED_PIN_11:
			return "ADIO8";
		default:
			return nullptr;
	}
	return nullptr;
}
